Repository wecode-bootcamp-korea/10-NoMac-frontend, pull requests merged in 2020-08, with the labels that each got.

#5 Add : 상세 리스트 페이지 구현
  .gitignore
  package.json
  public/images/bar.png
  public/images/fitness.png
  public/images/food.png
  public/images/internet.png
  public/images/loadingImg.png
  public/images/parking.png
  public/images/pin.png
  public/images/safety.png
  public/images/sun.png
  public/images/swimmer.png
  public/images/wifi.png
  public/index.html
  src/Components/DetailComponents/Aside.js
  src/Components/DetailComponents/AsideComponents/AsidePopular.js
  src/Components/DetailComponents/DetailItems.js
  src/Components/DetailComponents/GoogleMap.js
  src/Components/DetailComponents/HotelCalendar.js
  src/Components/DetailComponents/PeopleCheck.js
  src/Components/LoginComponent/EmailLogin.js
  src/Config.js
  src/MockData/DetailData.js
  src/MockData/SampleMap.js
  src/Pages/DetailListPage.js
  src/Routes.js
  yarn.lock
Labels: Status: 리뷰 요청

#7 Add: PostReview 컴포넌트 추가 및 업로드 기능 추가
  README.md
  package-lock.json
  public/images/charlogo.png
  public/images/feed01.png
  public/images/feed02.png
  public/images/feed03.png
  public/images/hawailhotel.jpg
  public/images/like.png
  public/images/monext.png
  public/images/moprev.png
  public/images/next.png
  src/Components/BtnMenu.js
  src/Components/LikeBtn.js
  src/Components/LoginComponent/SocialLogin.js
  src/Components/Modal.js
  src/Components/Nav.js
  src/Components/SelSlide.js
  src/Config.js
  src/MockData/MainData.js
  src/Pages/Main.js
  src/Pages/PostReview.js
  src/Pages/Review.js
  src/Routes.js
  src/index.js
Labels: Status: 수정 요청

#9 Add: 구글맵 클릭 이벤트 구현
  src/Components/DetailComponents/AsideComponents/AsidePopular.js
  src/Components/DetailComponents/GoogleMap.js
  src/Components/DetailComponents/PeopleCheck.js
  src/Pages/DetailListPage.js
Labels: Status: Accepted
